import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorials'}],
  blueprintsSidebar: [{ type: 'autogenerated', dirName: 'blueprints' }],
  // bestPracticesSidebar: [{type: 'autogenerated', dirName: 'best-practices'}],
  cafSidebar: [{ type: 'autogenerated', dirName: 'caf' }],

  // But you can create a sidebar manually

  bestPracticesSidebar: [
    {
      type: 'doc',
      id: 'best-practices/best-practices',
    },
    {
      type: 'category',
      label: 'Application Services',
      items: [
        {
          type: 'category',
          label: 'Application Operations Management',
          link: {
            type: 'generated-index',
            slug: '/best-practices/application-services/application-operations-management',
            keywords: ['application-operations-management'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/application-operations-management/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'API Gateway (APIG)',
          link: {
            type: 'generated-index',
            title: 'API Gateway (APIG)',
            slug: '/best-practices/application-services/api-gateway',
            keywords: ['api-gateway'],
          },
          items: [
            {
              type: 'doc',
              id: 'best-practices/application-services/api-gateway/selectively-exposing-cce-workloads-with-a-dedicated-gateway',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/api-gateway/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Application Performance Management',
          link: {
            type: 'generated-index',
            slug: '/best-practices/application-services/application-performance-management',
            keywords: ['application-performance-management'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/application-performance-management/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Distributed Message Service',
          link: {
            type: 'generated-index',
            title: 'Distributed Message Service',
            slug: '/best-practices/application-services/distributed-message-service',
            keywords: ['distributed-message-service'],
          },
          items: [
            {
              type: 'doc',
              id: 'best-practices/application-services/distributed-message-service/migrating-kafka-services',
            },
            {
              type: 'doc',
              id: 'best-practices/application-services/distributed-message-service/improving-kafka-message-processing-efficiency',
            },
            {
              type: 'doc',
              id: 'best-practices/application-services/distributed-message-service/optimizing-consumer-polling',
            },
            {
              type: 'doc',
              id: 'best-practices/application-services/distributed-message-service/configuring-message-accumulation-monitoring',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/distributed-message-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Simple Message Notification',
          link: {
            type: 'generated-index',
            slug: '/best-practices/application-services/simple-message-notification',
            keywords: ['simple-message-notification'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/simple-message-notification/index.html',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Big Data & Data Analysis',
      items: [
        {
          type: 'category',
          label: 'Cloud Search Service',
          link: {
            type: 'generated-index',
            slug: '/best-practices/big-data-and-data-analysis/cloud-search-service',
            keywords: ['cloud-search-service'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/cloud-search-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'DataArts Studio',
          link: {
            type: 'generated-index',
            slug: '/best-practices/big-data-and-data-analysis/data-arts-studio',
            keywords: ['data-arts-studio'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/data-arts-studio/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Data Ingestion Service',
          link: {
            type: 'generated-index',
            slug: '/best-practices/big-data-and-data-analysis/data-ingestion-service',
            keywords: ['data-ingestion-service'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/data-ingestion-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Data Lake Insight',
          link: {
            type: 'generated-index',
            slug: '/best-practices/big-data-and-data-analysis/data-lake-insight',
            keywords: ['data-lake-insight'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/data-lake-insight/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Data Warehouse Service',
          link: {
            type: 'generated-index',
            slug: '/best-practices/big-data-and-data-analysis/data-warehouse-service',
            keywords: ['data-warehouse-service'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/data-warehouse-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'ModelArts',
          link: {
            type: 'generated-index',
            slug: '/best-practices/big-data-and-data-analysis/modelarts',
            keywords: ['modelarts'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/modelarts/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'MapReduce Service',
          link: {
            type: 'generated-index',
            slug: '/best-practices/big-data-and-data-analysis/mapreduce-service',
            keywords: ['mapreduce-service'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/mapreduce-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Optical Character Recognition',
          link: {
            type: 'generated-index',
            slug: '/best-practices/big-data-and-data-analysis/optical-character-recognition',
            keywords: ['optical-character-recognition'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/optical-character-recognition/index.html',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Computing',
      items: [
        {
          type: 'category',
          label: 'Auto Scaling',
          link: {
            type: 'generated-index',
            slug: '/best-practices/computing/auto-scaling',
            keywords: ['auto-scaling'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/auto-scaling/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Bare Metal',
          link: {
            type: 'generated-index',
            slug: '/best-practices/computing/bare-metal-server',
            keywords: ['bare-metal-server'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/bare-metal-server/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Dedicated Host',
          link: {
            type: 'generated-index',
            slug: '/best-practices/computing/dedicated-host',
            keywords: ['dedicated-host'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/dedicated-host/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Elastic Cloud Server',
          link: {
            type: 'generated-index',
            title: 'Elastic Cloud Server',
            slug: '/best-practices/computing/elastic-cloud-server',
            keywords: ['elastic-cloud-server'],
          },
          items: [
            {
              type: 'doc',
              id: 'best-practices/computing/elastic-cloud-server/building-highly-available-web-server-clusters-with-keepalived',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/elastic-cloud-server/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'FunctionGraph',
          link: {
            type: 'generated-index',
            slug: '/best-practices/computing/function-graph',
            keywords: ['function-graph'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/function-graph/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Image Management Service',
          link: {
            type: 'generated-index',
            title: 'Image Management Service',
            slug: '/best-practices/computing/image-management-service',
            keywords: ['image-management-service'],
          },
          items: [
            {
              type: 'doc',
              id: 'best-practices/computing/image-management-service/migrating-service-data-across-accounts-data-disks',
            },
            // {
            //   type: 'doc',
            //   id: 'best-practices/computing/image-management-service/creating-a-linux-Image-using-virtualBox-and-an-iso-file',
            // },
            {
              type: 'doc',
              id: 'best-practices/computing/image-management-service/creating-a-linux-Image-using-virtualBox-and-an-iso-file',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/image-management-service/index.html',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Containers',
      items: [
        {
          type: 'category',
          label: 'Application Service Mesh',
          link: {
            type: 'generated-index',
            slug: '/best-practices/containers/application-service-mesh',
            keywords: ['application-service-mesh'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/application-service-mesh/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Cloud Container Engine',
          link: {
            type: 'generated-index',
            title: 'Cloud Container Engine',
            slug: '/best-practices/containers/cloud-container-engine',
            keywords: ['cloud-container-engine'],
          },
          items: [
            {
              type: 'doc',
              id: 'best-practices/containers/cloud-container-engine/prepare-cce-for-external-workloads',
            },
            {
              type: 'doc',
              id: 'best-practices/containers/cloud-container-engine/issue-an-acme-certificate-with-dns01-solver-in-cce',
            },
            {
              type: 'doc',
              id: 'best-practices/containers/cloud-container-engine/auto-scaling-based-on-elb-monitoring-metrics',
            },
            {
              type: 'category',
              label: 'Migrating Clusters from Other Clouds to CCE',
              link: {
                type: 'doc',
                id: 'best-practices/containers/cloud-container-engine/migrating-from-other_clouds-to-cce'
              },
              items: [
                {
                  type: 'doc',
                  id: 'best-practices/containers/cloud-container-engine/backup-kubernetes-objects',
                },
                {
                  type: 'doc',
                  id: 'best-practices/containers/cloud-container-engine/restore-kubernetes-objects',
                },
                {
                  type: 'doc',
                  id: 'best-practices/containers/cloud-container-engine/updating-resources',
                },
                {
                  type: 'doc',
                  id: 'best-practices/containers/cloud-container-engine/debugging-and-starting-the-application',
                },
              ],
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/cloud-container-engine/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Cloud Container Instance',
          link: {
            type: 'generated-index',
            slug: '/best-practices/containers/cloud-container-instance',
            keywords: ['cloud-container-instance'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/cloud-container-instance/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Software Repository for Container',
          link: {
            type: 'generated-index',
            title: 'Software Repository for Container',
            slug: '/best-practices/containers/software-repository',
            keywords: ['software-repository'],
          },
          items: [
            {
              type: 'doc',
              id: 'best-practices/containers/software-repository/migrating-container-images',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/software-repository-container/index.html',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Databases',
      items: [
        {
          type: 'category',
          label: 'Distributed Cache Service',
          link: {
            type: 'generated-index',
            title: 'Distributed Cache Service',
            slug: '/best-practices/databases/distributed-cache-service',
            keywords: ['distributed-cache-service'],
          },
          items: [
            {
              type: 'doc',
              id: 'best-practices/databases/distributed-cache-service/using-nginx-for-public-access-to-single-node-master-standby-or-proxy-cluster-dcs-redis-instances',
            },
            {
              type: 'doc',
              id: 'best-practices/databases/distributed-cache-service/using-ssh-tunneling-for-public-access-to-a-dcs-instance',
            },
            {
              type: 'doc',
              id: 'best-practices/databases/distributed-cache-service/using-elb-for-public-access-to-dcs',
            },
            {
              type: 'doc',
              id: 'best-practices/databases/distributed-cache-service/connecting-a-redis-client-to-dcs-through-cce',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/distributed-cache-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Distributed Database Middleware',
          link: {
            type: 'generated-index',
            title: 'Distributed Cache Service',
            slug: '/best-practices/databases/distributed-database-middleware',
            keywords: ['distributed-database-middleware'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/distributed-database-middleware/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Document Database Service',
          link: {
            type: 'generated-index',
            title: 'Document Database Service',
            slug: '/best-practices/databases/document-database-service',
            keywords: ['document-database-service'],
          },
          items: [
            {
              type: 'doc',
              id: 'best-practices/databases/document-database-service/from-ecs-hosted-mongodb-to-dds',
            },
            {
              type: 'doc',
              id: 'best-practices/databases/document-database-service/from-on-premises-mongodb-to-dds',
            },
            {
              type: 'doc',
              id: 'best-practices/databases/document-database-service/from-other-cloud-mongodb-to-dds',
            },
            {
              type: 'doc',
              id: 'best-practices/databases/document-database-service/how-do-replica-sets-achieve-high-availability-and-readwrite-splitting',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/document-database-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Data Replication Service',
          link: {
            type: 'generated-index',
            title: 'Distributed Cache Service',
            slug: '/best-practices/databases/data-replication-service',
            keywords: ['data-replication-service'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/data-replication-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'GaussDB (for MySQL)',
          link: {
            type: 'generated-index',
            title: 'Distributed Cache Service',
            slug: '/best-practices/databases/gaussdb-mysql',
            keywords: ['gaussdb-mysql'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/gaussdb-mysql/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'GeminiDB',
          link: {
            type: 'generated-index',
            title: 'Distributed Cache Service',
            slug: '/best-practices/databases/geminidb',
            keywords: ['geminidb'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/geminidb/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Relational Database Service',
          link: {
            type: 'generated-index',
            title: 'Relational Database Service',
            slug: '/best-practices/databases/relational-database-service',
            keywords: ['relational-database-service'],
          },
          items: [
            {
              type: 'doc',
              id: 'best-practices/databases/relational-database-service/configure-sg-for-rds-instances',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/relational-database-service/index.html',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Management & Deployment',
      items: [
        {
          type: 'category',
          label: 'Cloud Create',
          link: {
            type: 'doc',
            id: 'best-practices/management-and-deployment/cloud-create/cloud-create'
          },
          items: [
            // {
            //   type: 'category',
            //   label: 'Google Cloud',
            //   link: {
            //     type: 'doc',
            //     id: 'best-practices/management-and-deployment/cloud-create/google-cloud/google',
            //   },
            //   items: [
            //     {
            //       type: 'doc',
            //       id: 'best-practices/management-and-deployment/cloud-create/google-cloud/google-deploy',
            //     },
            //     {
            //       type: 'doc',
            //       id: 'best-practices/management-and-deployment/cloud-create/google-cloud/multi-region',
            //     },
            //     {
            //       type: 'doc',
            //       id: 'best-practices/management-and-deployment/cloud-create/google-cloud/application-dynamic-subnets',
            //     },
            //   ],
            // },
            // {
            //   type: 'category',
            //   label: 'Service catalogs',
            //   link: {
            //     type: 'doc',
            //     id: 'best-practices/management-and-deployment/cloud-create/service-catalogs/service-catalogs'
            //   },
            //   items: [
            //     {
            //       type: 'doc',
            //       id: 'best-practices/management-and-deployment/cloud-create/service-catalogs/openshift-template',
            //     },
            //   ],
            // },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/cloud-create/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Cloud Eye',
          link: {
            type: 'generated-index',
            title: 'Cloud Eye',
            slug: '/best-practices/management-and-deployment/cloud-eye',
            keywords: ['cloud-eye'],
          },
          items: [
            {
              type: 'doc',
              id: 'best-practices/management-and-deployment/cloud-eye/resource-group-monitoring',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/cloud-eye/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Config',
          link: {
            type: 'generated-index',
            slug: '/best-practices/management-and-deployment/config',
            keywords: ['config'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/config/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Cloud Trace Service',
          link: {
            type: 'generated-index',
            title: 'Cloud Trace Service',
            slug: '/best-practices/management-and-deployment/cloud-trace',
            keywords: ['cloud-trace'],
          },
          items: [
            {
              type: 'doc',
              id: 'best-practices/management-and-deployment/cloud-trace/auditing-and-analyzing-logins-and-logouts-with-functiongraph',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/cloud-trace-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Log Tank Service',
          link: {
            type: 'generated-index',
            slug: '/best-practices/management-and-deployment/log-tank-service',
            keywords: ['log-tank-service'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/log-tank-service/index.html',
            },
          ],
        },
        // {
        //   type: 'category',
        //   label: 'Resource Management Service',
        //   items: [
        //     {
        //       type: 'link',
        //       label: '📚 Go to Help Center',
        //       href: 'https://docs.otc.t-systems.com/resource-management-service/index.html',
        //     },
        //   ],
        // },
        {
          type: 'category',
          label: 'Resource Formation Service',
          link: {
            type: 'generated-index',
            slug: '/best-practices/management-and-deployment/resource-formation-service',
            keywords: ['resource-formation-service'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/resource-formation-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Tag Management Service',
          link: {
            type: 'generated-index',
            slug: '/best-practices/management-and-deployment/tag-management-service',
            keywords: ['tag-management-service'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/tag-management-service/index.html',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Networking',
      items: [
        {
          type: 'category',
          label: 'Direct Connect',
          link: {
            type: 'generated-index',
            slug: '/best-practices/networking/direct-connect',
            keywords: ['direct-connect'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/direct-connect/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Domain Name Service',
          link: {
            type: 'generated-index',
            title: 'Domain Name Service',
            slug: '/best-practices/networking/domain-name-service',
            keywords: ['domain-name-service'],
          },
          items: [
            {
              type: 'doc',
              id: 'best-practices/networking/domain-name-service/configuring-private-domain-names-for-ecss',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/domain-name-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Elastic IP',
          link: {
            type: 'generated-index',
            slug: '/best-practices/networking/elastic-ip',
            keywords: ['elastic-ip'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/elastic-ip/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Elastic Load Balancing',
          link: {
            type: 'generated-index',
            title: 'Elastic Load Balancing',
            slug: '/best-practices/networking/elastic-load-balancing',
            keywords: ['elastic-load-balancing'],
          },
          items: [
            {
              type: 'doc',
              id: 'best-practices/networking/elastic-load-balancing/using-advanced-forwarding-for-application-iteration',
            },
            {
              type: 'doc',
              id: 'best-practices/networking/elastic-load-balancing/routing-traffic-to-backend-servers-in-the-same-vpc-as-the-load-balancer',
            },
            {
              type: 'doc',
              id: 'best-practices/networking/elastic-load-balancing/routing-traffic-to-backend-servers-in-different-vpcs-from-the-load-balancer',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/elastic-load-balancing/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Enterprise Router',
          link: {
            type: 'generated-index',
            slug: '/best-practices/networking/enterprise-router',
            keywords: ['enterprise-router'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/enterprise-router/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'NAT Gateway',
          link: {
            type: 'generated-index',
            title: 'NAT Gateway',
            slug: '/best-practices/networking/nat-gateway',
            keywords: ['nat-gateway'],
          },
          items: [
            {
              type: 'doc',
              id: 'best-practices/networking/nat-gateway/using-a-public-nat-gateway-and-vpc-peering-to-enable-communications-between-vpcs-and-the-internet',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/nat-gateway/index.html',
            },

          ],
        },
        {
          type: 'category',
          label: 'Private Link Access Service',
          link: {
            type: 'generated-index',
            slug: '/best-practices/networking/private-link-access-service',
            keywords: ['private-link-access-service'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/private-link-access-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Secure Mail Gateway',
          link: {
            type: 'generated-index',
            slug: '/best-practices/networking/secure-mail-gateway',
            keywords: ['secure-mail-gateway'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/secure-mail-gateway/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Virtual Private Cloud',
          link: {
            type: 'generated-index',
            title: 'Virtual Private Cloud',
            slug: '/best-practices/networking/virtual-private-cloud',
            keywords: ['virtual-private-cloud'],
          },
          items: [
            {
              type: 'doc',
              id: 'best-practices/networking/virtual-private-cloud/vpc-and-subnet-planning-suggestions',
            },
            {
              type: 'doc',
              id: 'best-practices/networking/virtual-private-cloud/unsupported-vpc-peering-configurations',
            },
            {
              type: 'doc',
              id: 'best-practices/networking/virtual-private-cloud/deploying-containers-that-can-communicate-with-each-other-on-ecss',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/virtual-private-cloud/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'VPC Endpoint',
          link: {
            type: 'generated-index',
            slug: '/best-practices/networking/vpc-endpoint',
            keywords: ['vpc-endpoint'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/vpc-endpoint/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Virtual Private Network',
          link: {
            type: 'generated-index',
            title: 'Virtual Private Network',
            slug: '/best-practices/networking/virtual-private-network',
            keywords: ['virtual-private-network'],
          },
          items: [
            {
              type: 'doc',
              id: 'best-practices/networking/virtual-private-network/connecting-multiple-on-premises-branch-networks-through-a-vpn-hub',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/virtual-private-network/index.html',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Security Services',
      items: [
        {
          type: 'category',
          label: 'Anti DDoS',
          link: {
            type: 'generated-index',
            slug: '/best-practices/security-services/anti-ddos',
            keywords: ['anti-ddos'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/anti-ddos/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Cloud Firewall',
          link: {
            type: 'generated-index',
            slug: '/best-practices/security-services/cloud-firewall',
            keywords: ['cloud-firewall'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/cloud-firewall/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Database Security Service',
          link: {
            type: 'generated-index',
            slug: '/best-practices/security-services/database-security-service',
            keywords: ['database-security-service'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/database-security-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Host Security Service',
          link: {
            type: 'generated-index',
            title: 'Host Security Service',
            slug: '/best-practices/security-services/host-security-service',
            keywords: ['host-security-service'],
          },
          items: [
            {
              type: 'category',
              label: 'Using HSS and CBR to Defend Against Ransomware',
              items: [
                {
                  type: 'doc',
                  id: 'best-practices/security-services/host-security-service/using-hss-and-cbr-to-defend-against-ransomware/overview',
                },
                {
                  type: 'doc',
                  id: 'best-practices/security-services/host-security-service/using-hss-and-cbr-to-defend-against-ransomware/resources-and-costs',
                },
                {
                  type: 'category',
                  label: 'Defense Measures',
                  items: [
                    {
                      type: 'doc',
                      id: 'best-practices/security-services/host-security-service/using-hss-and-cbr-to-defend-against-ransomware/defense-measures/identifying-and-fixing-ransomware',
                    },
                    {
                      type: 'doc',
                      id: 'best-practices/security-services/host-security-service/using-hss-and-cbr-to-defend-against-ransomware/defense-measures/enabling-ransomware-prevention-and-backup',
                    },
                    {
                      type: 'doc',
                      id: 'best-practices/security-services/host-security-service/using-hss-and-cbr-to-defend-against-ransomware/defense-measures/restoring-backup-data',
                    }
                  ],
                },
              ],
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/host-security-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Identity and Access Management',
          link: {
            type: 'generated-index',
            title: 'Identity and Access Management',
            slug: '/best-practices/security-services/iam',
            keywords: ['iam'],
          },
          items: [
            {
              type: 'doc',
              id: 'best-practices/security-services/iam/recommendations-for-using-iam',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/identity-access-management/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Key Management Service',
          link: {
            type: 'generated-index',
            slug: '/best-practices/security-services/key-management-service',
            keywords: ['key-management-service'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/key-management-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Web Application Firewall',
          link: {
            type: 'generated-index',
            title: 'Web Application Firewall',
            slug: '/best-practices/security-services/web-application-firewall',
            keywords: ['web-application-firewall'],
          },
          items: [
            {
              type: 'doc',
              id: 'best-practices/security-services/web-application-firewall/combining-waf-and-layer-7-load-balancers-to-protect-services-over-any-ports',
            },
            {
              type: 'doc',
              id: 'best-practices/security-services/web-application-firewall/using-lts-to-quickly-query-and-analyze-waf-access-logs',
            },
            {
              type: 'doc',
              id: 'best-practices/security-services/web-application-firewall/configuring-anti-crawler-rules-to-prevent-crawler-attacks',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/web-application-firewall/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Dedicated Web Application Firewall',
          link: {
            type: 'generated-index',
            slug: '/best-practices/security-services/web-application-firewall-dedicated',
            keywords: ['web-application-firewall-dedicated'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/web-application-firewall-dedicated/index.html',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Storage',
      items: [
        {
          type: 'category',
          label: 'Cloud Backup and Recovery',
          link: {
            type: 'generated-index',
            slug: '/best-practices/storage/cloud-backup-recovery',
            keywords: ['cloud-backup-recovery'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/cloud-backup-recovery/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Cloud Server Backup Service',
          link: {
            type: 'generated-index',
            slug: '/best-practices/storage/cloud-server-backup-service',
            keywords: ['cloud-server-backup-service'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/cloud-server-backup-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Elastic Volume Service',
          link: {
            type: 'generated-index',
            title: 'Elastic Volume Service',
            slug: '/best-practices/storage/elastic-volume-service',
            keywords: ['elastic-volume-service'],
          },
          items: [
            {
              type: 'doc',
              id: 'best-practices/storage/elastic-volume-service/raid-array-creation-with-evs-disks',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/elastic-volume-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Object Storage Service',
          link: {
            type: 'generated-index',
            title: 'Object Storage Service',
            slug: '/best-practices/storage/object-storage-service',
            keywords: ['object-storage-service'],
          },
          items: [
            {
              type: 'doc',
              id: 'best-practices/storage/object-storage-service/accessing-obs-through-an-nginx-reverse-proxy',
            },
            {
              type: 'doc',
              id: 'best-practices/storage/object-storage-service/migrating-local-data-to-obs',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/object-storage-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Storage Disaster Recovery Service',
          link: {
            type: 'generated-index',
            slug: '/best-practices/storage/storage-disaster-recovery-service',
            keywords: ['storage-disaster-recovery-service'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/storage-disaster-recovery-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Scalable File Service',
          link: {
            type: 'generated-index',
            slug: '/best-practices/storage/scalable-file-service',
            keywords: ['scalable-file-service'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/scalable-file-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Volume Backup Service',
          link: {
            type: 'generated-index',
            slug: '/best-practices/storage/volume-backup-service',
            keywords: ['volume-backup-service'],
          },
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/volume-backup-service/index.html',
            },
          ],
        },
      ],
    },
    // {
    //   type: 'category',
    //   label: 'Getting Started',
    //   items: [
    //     {
    //       type: 'doc',
    //       id: 'doc1',
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Docusaurus',
    //   items: [
    //     {
    //       type: 'doc',
    //       id: 'doc2',
    //     },
    //     {
    //       type: 'doc',
    //       id: 'doc3',
    //     },
    //   ],
    // },
    // {
    //   type: 'link',
    //   label: 'Learn more',
    //   href: 'https://example.com',
    // },
    // {
    //   type: 'link',
    //   label: 'Portfolio Roadmap',
    //   href: 'https://www.open-telekom-cloud.com/en/products-services/roadmap',
    // },
    // {
    //   type: 'link',
    //   label: 'Status Dashboard',
    //   href: 'https://status.otc-service.com/',
    // },
  ],

};

export default sidebars;
