import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorials'}],
  blueprintsSidebar: [{type: 'autogenerated', dirName: 'blueprints'}],
  // bestPracticesSidebar: [{type: 'autogenerated', dirName: 'best-practices'}],
  cafSidebar: [{type: 'autogenerated', dirName: 'caf'}],

  // But you can create a sidebar manually
  
  // tutorialSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  // ],

  mySidebar: [
    {
      type: 'doc',
      id: 'best-practices',
    },
    {
      type: 'category',
      label: 'Application Services',
      items: [
        {
          type: 'category',
          label: 'Auto-Scaling',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Bare Metal',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Dedicated Host',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Elastic Cloud Server',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'FunctionGraph',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Image Management Service',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'link',
          label: 'Go to Documentation Center',
          href: 'https://example.com',
        },
      ],
    },
    {
      type: 'category',
      label: 'Big Data & Data Analysis',
      items: [
        {
          type: 'category',
          label: 'Auto-Scaling',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Bare Metal',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Dedicated Host',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Elastic Cloud Server',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'FunctionGraph',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Image Management Service',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'link',
          label: 'Go to Documentation Center',
          href: 'https://example.com',
        },
      ],
    },
    {
      type: 'category',
      label: 'Computing',
      items: [
        {
          type: 'category',
          label: 'Auto-Scaling',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Bare Metal',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Dedicated Host',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Elastic Cloud Server',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'FunctionGraph',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Image Management Service',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'link',
          label: 'Go to Documentation Center',
          href: 'https://example.com',
        },
      ],
    },
    {
      type: 'category',
      label: 'Containers',
      items: [
        {
          type: 'category',
          label: 'Auto-Scaling',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Bare Metal',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Dedicated Host',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Elastic Cloud Server',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'FunctionGraph',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Image Management Service',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'link',
          label: 'Go to Documentation Center',
          href: 'https://example.com',
        },
      ],
    },
    {
      type: 'category',
      label: 'Databases',
      items: [
        {
          type: 'category',
          label: 'Auto-Scaling',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Bare Metal',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Dedicated Host',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Elastic Cloud Server',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'FunctionGraph',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Image Management Service',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'link',
          label: 'Go to Documentation Center',
          href: 'https://example.com',
        },
      ],
    },
    {
      type: 'category',
      label: 'Management & Deployment',
      items: [
        {
          type: 'category',
          label: 'Auto-Scaling',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Bare Metal',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Dedicated Host',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Elastic Cloud Server',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'FunctionGraph',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Image Management Service',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'link',
          label: 'Go to Documentation Center',
          href: 'https://example.com',
        },
      ],
    },
    {
      type: 'category',
      label: 'Networking',
      items: [
        {
          type: 'category',
          label: 'Auto-Scaling',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Bare Metal',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Dedicated Host',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Elastic Cloud Server',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'FunctionGraph',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Image Management Service',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'link',
          label: 'Go to Documentation Center',
          href: 'https://example.com',
        },
      ],
    },
    {
      type: 'category',
      label: 'Security Services',
      items: [
        {
          type: 'category',
          label: 'Auto-Scaling',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Bare Metal',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Dedicated Host',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Elastic Cloud Server',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'FunctionGraph',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Image Management Service',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'link',
          label: 'Go to Documentation Center',
          href: 'https://example.com',
        },
      ],
    },
    {
      type: 'category',
      label: 'Storage',
      items: [
        {
          type: 'category',
          label: 'Auto-Scaling',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Bare Metal',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Dedicated Host',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Elastic Cloud Server',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'FunctionGraph',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'category',
          label: 'Image Management Service',
          items: [
            {
              type: 'link',
              label: 'Go to Documentation Center',
              href: 'https://example.com',
            },
          ],
        },
        {
          type: 'link',
          label: 'Go to Documentation Center',
          href: 'https://example.com',
        },
      ],
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {
          type: 'doc',
          id: 'doc1',
        },
      ],
    },
    {
      type: 'category',
      label: 'Docusaurus',
      items: [
        {
          type: 'doc',
          id: 'doc2',
        },
        {
          type: 'doc',
          id: 'doc3',
        },
      ],
    },
    {
      type: 'link',
      label: 'Learn more',
      href: 'https://example.com',
    },
  ],
   
};

export default sidebars;
