import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorials'}],
  blueprintsSidebar: [{ type: 'autogenerated', dirName: 'blueprints' }],
  // bestPracticesSidebar: [{type: 'autogenerated', dirName: 'best-practices'}],
  cafSidebar: [{ type: 'autogenerated', dirName: 'caf' }],

  // But you can create a sidebar manually

  bestPracticesSidebar: [
    {
      type: 'doc',
      id: 'best-practices/best-practices',
    },
    {
      type: 'category',
      label: 'Application Services',
      items: [
        {
          type: 'category',
          label: 'Application Operations Management',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/application-operations-management/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'API Gateway (APIG)',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/api-gateway/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Distributed Message Service',
          items: [
            {
              type: 'doc',
              id: 'best-practices/application-services/distributed-message-service/migrating-kafka-services',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/distributed-message-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Simple Message Notification',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/simple-message-notification/index.html',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Big Data & Data Analysis',
      items: [
        {
          type: 'category',
          label: 'Cloud Search Service',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/cloud-search-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'DataArts Studio',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/data-arts-studio/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Data Ingestion Service',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/data-ingestion-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Data Lake Insight',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/data-lake-insight/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Data Warehouse Service',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/data-warehouse-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'ModelArts',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/modelarts/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'MapReduce Service',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/mapreduce-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Optical Character Recognition',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/optical-character-recognition/index.html',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Computing',
      items: [
        {
          type: 'category',
          label: 'Auto-Scaling',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/auto-scaling/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Bare Metal',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/bare-metal-server/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Dedicated Host',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/dedicated-host/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Elastic Cloud Server',
          items: [
            // {
            //   type: 'doc',
            //   id: 'best-practices/computing/elastic-cloud-server/building-highly-available-web-server-clusters-with-keepalived',
            // },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/elastic-cloud-server/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'FunctionGraph 🔥',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/function-graph/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Image Management Service',
          items: [
            {
              type: 'doc',
              id: 'best-practices/computing/image-management-service/migrating-service-data-across-accounts-data-disks',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/image-management-service/index.html',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Containers',
      items: [
        {
          type: 'category',
          label: 'Cloud Container Engine',
          items: [
            {
              type: 'doc',
              id: 'best-practices/containers/cloud-container-engine/auto-scaling-based-on-elb-monitoring-metrics',
            },
            {
              type: 'category',
              label: 'Migrating Clusters from Other Clouds to CCE',
              link: {
                type: 'doc', 
                id: 'best-practices/containers/cloud-container-engine/migrating-from-other_clouds-to-cce'
              },
              items: [
                {
                  type: 'doc',
                  id: 'best-practices/containers/cloud-container-engine/backup-kubernetes-objects',
                },
                {
                  type: 'doc',
                  id: 'best-practices/containers/cloud-container-engine/restore-kubernetes-objects',
                },
                {
                  type: 'doc',
                  id: 'best-practices/containers/cloud-container-engine/updating-resources',
                },   
                {
                  type: 'doc',
                  id: 'best-practices/containers/cloud-container-engine/debugging-and-starting-the-application',
                },   
              ],
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/cloud-container-engine/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Software Repository for Container',
          items: [
            {
              type: 'doc',
              id: 'best-practices/containers/software-repository/migrating-container-images',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/software-repository-container/index.html',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Databases',
      items: [
        {
          type: 'category',
          label: 'Distributed Cache Service',
          items: [
            {
              type: 'doc',
              id: 'best-practices/databases/distributed-cache-service/using-nginx-for-public-access-to-single-node-master-standby-or-proxy-cluster-dcs-redis-instances',
            },
            {
              type: 'doc',
              id: 'best-practices/databases/distributed-cache-service/using-ssh-tunneling-for-public-access-to-a-dcs-instance',
            },
            {
              type: 'doc',
              id: 'best-practices/databases/distributed-cache-service/using-elb-for-public-access-to-dcs',
            },
            {
              type: 'doc',
              id: 'best-practices/databases/distributed-cache-service/connecting-a-redis-client-to-dcs-through-cce',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/distributed-cache-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Distributed Database Middleware',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/distributed-database-middleware/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Document Database Service',
          items: [
            {
              type: 'doc',
              id: 'best-practices/databases/document-database-service/from-ecs-hosted-mongodb-to-dds',
            },
            {
              type: 'doc',
              id: 'best-practices/databases/document-database-service/from-on-premises-mongodb-to-dds',
            },
            {
              type: 'doc',
              id: 'best-practices/databases/document-database-service/from-other-cloud-mongodb-to-dds',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/document-database-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Data Replication Service',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/data-replication-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'GaussDB (for MySQL)',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/gaussdb-mysql/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'GaussDB NoSQL',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/gaussdb-nosql/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Relational Database Service',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/relational-database-service/index.html',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Management & Deployment',
      items: [
        {
          type: 'category',
          label: 'Application Performance Management',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/application-performance-management/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Cloud Create 🔥',
          link: {
            type: 'doc', 
            id: 'best-practices/management-and-deployment/cloud-create/cloud-create'
          },
          items: [
            {
              type: 'category',
              label: 'Google Cloud',
              link: {
                type: 'doc', 
                id: 'best-practices/management-and-deployment/cloud-create/google-cloud/google',
              },
              items: [
                {
                  type: 'doc',
                  id: 'best-practices/management-and-deployment/cloud-create/google-cloud/google-deploy',
                },
                {
                  type: 'doc',
                  id: 'best-practices/management-and-deployment/cloud-create/google-cloud/multi-region',
                },
                {
                  type: 'doc',
                  id: 'best-practices/management-and-deployment/cloud-create/google-cloud/application-dynamic-subnets',
                },
              ],
            },
            {
              type: 'category',
              label: 'Service catalogs',
              // link: {
              //   type: 'generated-index',
              //   description: 'Learn about the most important Docusaurus concepts!',
              //   slug: '/best-practices/management-and-deployment/cloud-create/service-catalogs',
              //   keywords: ['cloud-create'],
              // },
              link: {
                type: 'doc', 
                id: 'best-practices/management-and-deployment/cloud-create/service-catalogs/service-catalogs'
              },
              items: [
                {
                  type: 'doc',
                  id: 'best-practices/management-and-deployment/cloud-create/service-catalogs/openshift-template',
                },
              ],
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/cloud-create/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Cloud Eye',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/cloud-eye/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Cloud Trace Service',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/cloud-trace-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Log Tank Service',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/log-tank-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Resource Management Service',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/resource-management-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Tag Management Service',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/tag-management-service/index.html',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Networking',
      items: [
        {
          type: 'category',
          label: 'Direct Connect',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/direct-connect/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Domain Name Service',
          items: [
            {
              type: 'doc',
              id: 'best-practices/networking/domain-name-service/configuring-private-domain-names-for-ecss',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/domain-name-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Elastic IP',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/elastic-ip/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Elastic Load Balancing',
          items: [
            {
              type: 'doc',
              id: 'best-practices/networking/elastic-load-balancing/using-advanced-forwarding-for-application-iteration',
            },
            {
              type: 'doc',
              id: 'best-practices/networking/elastic-load-balancing/routing-traffic-to-backend-servers-in-the-same-vpc-as-the-load-balancer',
            },
            {
              type: 'doc',
              id: 'best-practices/networking/elastic-load-balancing/routing-traffic-to-backend-servers-in-different-vpcs-from-the-load-balancer',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/elastic-load-balancing/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Enterprise Router',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/enterprise-router/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'NAT Gateway',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/nat-gateway/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Private Link Access Service',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/private-link-access-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Secure Mail Gateway',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/secure-mail-gateway/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Virtual Private Cloud',
          items: [
            {
              type: 'doc',
              id: 'best-practices/networking/virtual-private-cloud/vpc-and-subnet-planning-suggestions',
            },
            {
              type: 'doc',
              id: 'best-practices/networking/virtual-private-cloud/unsupported-vpc-peering-configurations',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/virtual-private-cloud/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'VPC Endpoint',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/vpc-endpoint/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Virtual Private Network',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/virtual-private-network/index.html',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Security Services',
      items: [
        {
          type: 'category',
          label: 'Anti DDoS',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/anti-ddos/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Database Security Service',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/database-security-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Host Security Service',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/host-security-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Identity and Access Management',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/identity-access-management/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Key Management Service',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/key-management-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Web Application Firewall',
          items: [
            {
              type: 'doc',
              id: 'best-practices/security-services/web-application-firewall/combining-waf-and-layer-7-load-balancers-to-protect-services-over-any-ports',
            },
            {
              type: 'doc',
              id: 'best-practices/security-services/web-application-firewall/using-lts-to-quickly-query-and-analyze-waf-access-logs',
            },
            {
              type: 'doc',
              id: 'best-practices/security-services/web-application-firewall/configuring-anti-crawler-rules-to-prevent-crawler-attacks',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/web-application-firewall/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Dedicated Web Application Firewall',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/web-application-firewall-dedicated/index.html',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Storage',
      items: [
        {
          type: 'category',
          label: 'Cloud Backup and Recovery',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/cloud-backup-recovery/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Cloud Server Backup Service',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/cloud-server-backup-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Elastic Volume Service',
          items: [
            {
              type: 'doc',
              id: 'best-practices/storage/elastic-volume-service/raid-array-creation-with-evs-disks',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/elastic-volume-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Object Storage Service',
          items: [
            {
              type: 'doc',
              id: 'best-practices/storage/object-storage-service/accessing-obs-through-an-nginx-reverse-proxy',
            },
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/object-storage-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Storage Disaster Recovery Service',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/storage-disaster-recovery-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Scalable File Service',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/scalable-file-service/index.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Volume Backup Service',
          items: [
            {
              type: 'link',
              label: '📚 Go to Help Center',
              href: 'https://docs.otc.t-systems.com/volume-backup-service/index.html',
            },
          ],
        },
      ],
    },
    // {
    //   type: 'category',
    //   label: 'Getting Started',
    //   items: [
    //     {
    //       type: 'doc',
    //       id: 'doc1',
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Docusaurus',
    //   items: [
    //     {
    //       type: 'doc',
    //       id: 'doc2',
    //     },
    //     {
    //       type: 'doc',
    //       id: 'doc3',
    //     },
    //   ],
    // },
    // {
    //   type: 'link',
    //   label: 'Learn more',
    //   href: 'https://example.com',
    // },
    // {
    //   type: 'link',
    //   label: 'Portfolio Roadmap',
    //   href: 'https://www.open-telekom-cloud.com/en/products-services/roadmap',
    // },
    // {
    //   type: 'link',
    //   label: 'Status Dashboard',
    //   href: 'https://status.otc-service.com/',
    // },
  ],

};

export default sidebars;
