// Auto-generated by @telekom-ods/react-ui-kit postinstall
// Adjust values as needed. Import this file once in your app entry (e.g. src/main.tsx).
window.__ODS_TELEMETRY__ = { projectName: "docs-next", includePath: true, disableTelemetry: false, };
window.__ODS_TELEMETRY_ENDPOINT__ = "https://ods-telemetry-server.dev.oa.yo-digital.com/telemetry";
window.__ODS_TELEMETRY_API_KEY__ = "pk_2fa5bb985cb82193e5291d6b838da57bc48e81e1ae3edeb18d08af202f60b586";

// To disable telemetry at runtime set:
// window._DISABLE_TELEMETRY_ = true;
